# Generated by Django 3.0.8 on 2020-08-15 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_person_name', models.TextField()),
                ('person_image', models.ImageField(default='', upload_to='tree\\images')),
                ('person_relation', models.CharField(max_length=20)),
                ('person_relation_with_name', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
