# Generated by Django 3.0.8 on 2020-08-16 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='login_username',
            field=models.CharField(default='', max_length=50),
        ),
    ]
