# Generated by Django 3.0.8 on 2020-07-20 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0002_images_person_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='person_image',
            field=models.ImageField(default='', upload_to='tree\\images'),
        ),
    ]
