# Generated by Django 3.0.8 on 2020-07-21 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0003_auto_20200720_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image_person_name',
            field=models.TextField(),
        ),
    ]
