# Generated by Django 3.0.8 on 2020-08-12 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0004_auto_20200721_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='person_relation',
            field=models.CharField(choices=[('father', 'FATHER'), ('mother', 'MOTHER'), ('cousin', 'COUSIN'), ('sibling', 'SIBLING')], default='select your relation', max_length=20),
        ),
    ]
