# Generated by Django 3.0.8 on 2020-08-12 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0005_images_person_relation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='person_relation',
            field=models.CharField(max_length=20),
        ),
    ]
