# Generated by Django 3.0.8 on 2020-08-17 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0005_auto_20200817_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='person_relation_with_name',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
