# Generated by Django 3.0.8 on 2020-08-12 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0006_auto_20200812_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='person_relation_with_name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
