# Generated by Django 3.0.8 on 2020-08-15 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0008_signup'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='user_email',
            field=models.EmailField(default='', max_length=50),
        ),
    ]
